version: '3.8'

services:
  webapp-test:
    image: webapp-test
    container_name: webapp-test
    restart: on-failure
    build:
      context: ./webapp
      dockerfile: Dockerfile
      target: prod
    ports:
      - 8080:8080

  cypress:
    image: "cypress/included:4.10.0"
    container_name: cypress
    restart: on-failure
    environment:
      - CYPRESS_baseUrl=http://webapp-test:8080/orcaal
      - CYPRESS_VIDEO=false
    depends_on:
      - webapp-test
    working_dir: /e2e
    volumes:
      - ./webapp:/e2e
      - /webapp/node_modules
