name: Code quality

on:
  push:
  pull_request:
    branches: [master]
    types: [opened, synchronize]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: eu-west-1

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tool:
          [
            "isort",
            "black",
            "pyupgrade",
            "flake8",
            "trailing-whitespace",
            "end-of-file-fixer",
            "fix-byte-order-marker",
            "eslint",
          ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pre-commit
          pre-commit install
      - name: Run ${{ matrix.tool }}
        run: |
          pre-commit run ${{ matrix.tool }} --all-files
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run docker compose
        run: docker-compose -f docker-compose.test.yml up --build --exit-code-from pytest --abort-on-container-exit
