name: Dockerized tests

on:
  push:
    branches:
      - docker-compose-for-dev
  pull_request:
    branches: [docker-compose-for-dev]
    types: [opened, synchronize]
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: eu-west-1

jobs:
  testing:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: run docker compose backend
        run: docker-compose -f docker-compose.test.backend.yml up --build --exit-code-from pytest --abort-on-container-exit
      - name: clean up docker compose backend
        run: docker-compose -f docker-compose.test.backend.yml down
      - name: run docker compose frontend
        run: docker-compose -f docker-compose.test.frontend.yml up --build --exit-code-from cypress --abort-on-container-exit
      - name: clean up docker compose frontend
        run: docker-compose -f docker-compose.test.frontend.yml down
