name: Scheduled Check

on:
  schedule:
    - cron:  '30 17 * * 3,6'
    
  pull_request:

jobs:
  scheduled_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://orcasound.github.io/orcaal/
          follow-redirect: false
          max-attempts: 3
          retry-delay: 5s
          retry-all: false
